const qualityOne =
  'https://wow.zamimg.com/images/wow/TextureAtlas/live/professions-chaticon-quality-tier1.png'
const qualityTwo =
  'https://wow.zamimg.com/images/wow/TextureAtlas/live/professions-chaticon-quality-tier2.png'
const qualityThree =
  'https://wow.zamimg.com/images/wow/TextureAtlas/live/professions-chaticon-quality-tier3.png'

export const GEMS_DATA_ = {
  228646: {
    id: '228646',
    name: 'Legendary Skipper Citrine',
    ico: 'inv_siren_isle_singing_citrine_prismatic',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Your spells and abilities have a chance to cast a random Singing Citrine effect at 150% effectiveness.',
  },
  228639: {
    id: '228639',
    name: 'Fathomdweller Runed Citrine',
    ico: 'inv_siren_isle_searuned_citrine_blue',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Grants 39740.006 / 1510.133 Mastery. In addition, all other Singing Citrine effects are increased based on your total Mastery.',
  },
  228638: {
    id: '228638',
    name: 'Stormbringers Runed Citrine',
    ico: 'inv_siren_isle_searuned_citrine_red',
    quality: '',
    stats: '',
    statsTitle: '',
  },
  213743: {
    id: '213743',
    name: 'Culminating Blasphemite',
    ico: 'item_cutmetagemb',
    quality: qualityThree,
    stats: '181PS 0.15% CritD',
    statsTitle:
      '+181 Primary Stat and +0.15% Critical Effect per unique Algari gem color',
  },
  213742: {
    id: '213742',
    name: 'Culminating Blasphemite',
    ico: 'item_cutmetagemb',
    quality: qualityTwo,
    stats: '159PS 0.15% CritD',
    statsTitle:
      '+159 Primary Stat and +0.15% Critical Effect per unique Algari gem color',
  },
  213741: {
    id: '213741',
    name: 'Culminating Blasphemite',
    ico: 'item_cutmetagemb',
    quality: qualityOne,
    stats: '136PS 0.15% CritD',
    statsTitle:
      '+136 Primary Stat and +0.15% Critical Effect per unique Algari gem color',
  },

  228640: {
    id: '228640',
    name: "Windsinger's Runed Citrine",
    ico: 'inv_siren_isle_searuned_citrine_pink',
    quality: '',
    stats: '925 hss',
    statsTitle: 'Equip: Grants 925 of your highest secondary stat.',
  },
  228634: {
    id: '228634',
    name: "Thunderlord's Crackling Citrine",
    ico: 'inv_siren_isle_stormcharged_citrine_blue',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Your spells and abilities have a chance to zap an enemy dealing 211376 Nature damage.',
  },
  228636: {
    id: '228636',
    name: "Undersea Overseer's Citrine",
    ico: 'inv_siren_isle_stormcharged_citrine_green',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Your spells and abilities have a chance to drench an enemy in freezing seawater that bounces to 2 nearby enemies, dealing 140773.74 Frost damage to each of them.',
  },
  213746: {
    id: '213746',
    name: 'Elusive Blasphemite',
    ico: 'inv_misc_gem_x4_metagem_cut',
    quality: qualityThree,
    stats: '181 PStat/+2% MS',
    statsTitle:
      'Unique-Equipped: Algari Diamond (1) +181 Primary Stat and +2% Movement Speed per unique Algari gem color',
  },
  213745: {
    id: '213745',
    name: 'Elusive Blasphemite',
    ico: 'inv_misc_gem_x4_metagem_cut',
    quality: qualityTwo,
    stats: '159 PStat/+2% MS',
    statsTitle:
      'Unique-Equipped: Algari Diamond (1)+159 Primary Stat and +2% Movement Speed per unique Algari gem color',
  },
  213744: {
    id: '213744',
    name: 'Elusive Blasphemite',
    ico: 'inv_misc_gem_x4_metagem_cut',
    quality: qualityOne,
    stats: '136 PStat/+2% MS',
    statsTitle:
      'Unique-Equipped: Algari Diamond (1)+136 Primary Stat and +2% Movement Speed per unique Algari gem color',
  },
  228644: {
    id: '228644',
    name: "Mariner's Hallowed Citrine",
    ico: 'inv_siren_isle_blessed_citrine_purple',
    quality: '',
    stats: 'heal allys',
    statsTitle:
      'Equip: Your spells and abilities have a chance to bathe an ally in restorative water that jumps to 2 nearby allies, restoring 211268.4 health to each of them.',
  },
  228648: {
    id: '228648',
    name: "Roaring War-Queen's Citrine",
    ico: 'inv_siren_isle_singing_citrine_yellow',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Your spells and abilities have a low chance of triggering the Singing Thunder Citrine effects of 4 nearby allies. Whenever an allied player dies, this effect is triggered immediately.',
  },
  213482: {
    id: '213482',
    name: 'Masterful Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_3',
    quality: qualityThree,
    stats: '+147 Haste and +49 Mastery',
    statsTitle: '+147 Haste and +49 Mastery',
  },
  213481: {
    id: '213481',
    name: 'Masterful Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_3',
    quality: qualityTwo,
    stats: '+132 Haste and +44 Mastery',
    statsTitle: '+132 Haste and +44 Mastery',
  },
  213480: {
    id: '213480',
    name: 'Masterful Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_3',
    quality: qualityOne,
    stats: '+118 Haste and +39 Mastery',
    statsTitle: '+118 Haste and +39 Mastery',
  },
  228643: {
    id: '228643',
    name: "Old Salt's Bardic Citrine",
    ico: 'inv_siren_isle_blessed_citrine_red',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Your spells and abilities have a chance to whisper a sea shanty to 5 nearby allies, healing them for 176128.86 health over 5 sec.',
  },
  228642: {
    id: '228642',
    name: "Storm Sewer's Citrine",
    ico: 'inv_siren_isle_blessed_citrine_blue',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Your spells and abilities have a chance to shield an ally with lightning, absorbing the next 317010.39 damage taken for 10 sec. While the shield persists, attackers take 10% of the amount absorbed as Nature damage.',
  },
  213494: {
    id: '213494',
    name: 'Quick Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_3',
    quality: qualityThree,
    stats: '+147 Mastery and +49 Haste',
    statsTitle: '+147 Mastery and +49 Haste',
  },
  213493: {
    id: '213493',
    name: 'Quick Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_3',
    quality: qualityTwo,
    stats: '+132 Mastery and +44 Haste',
    statsTitle: '+132 Mastery and +44 Haste',
  },
  213492: {
    id: '213492',
    name: 'Quick Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_3',
    quality: qualityOne,
    stats: '+118 Mastery and +39 Haste',
    statsTitle: '+118 Mastery and +39 Haste',
  },
  228635: {
    id: '228635',
    name: "Squall Sailor's Citrine",
    ico: 'inv_siren_isle_stormcharged_citrine_turquoise',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Your spells and abilities have a chance to slice 5 enemies with a rushing seabreeze, dealing 117383.31 Nature damage to each of them.',
  },
  213479: {
    id: '213479',
    name: 'Deadly Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_2',
    quality: qualityThree,
    stats: '+147 Haste and +49 Critical Strike',
    statsTitle: '+147 Haste and +49 Critical Strike',
  },
  213478: {
    id: '213478',
    name: 'Deadly Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_2',
    quality: qualityTwo,
    stats: '+132 Haste and +44 Critical Strike',
    statsTitle: '+132 Haste and +44 Critical Strike',
  },
  213477: {
    id: '213477',
    name: 'Deadly Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_2',
    quality: qualityOne,
    stats: '+118 Haste and +39 Critical Strike',
    statsTitle: '+118 Haste and +39 Critical Strike',
  },
  213455: {
    id: '213455',
    name: 'Quick Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_3',
    quality: qualityThree,
    stats: '+147 Critical Strike and +49 Haste',
    statsTitle: '+147 Critical Strike and +49 Haste',
  },
  213454: {
    id: '213454',
    name: 'Quick Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_3',
    quality: qualityTwo,
    stats: '+132 Critical Strike and +44 Haste',
    statsTitle: '+132 Critical Strike and +44 Haste',
  },
  213453: {
    id: '213453',
    name: 'Quick Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_3',
    quality: qualityOne,
    stats: '+118 Critical Strike and +39 Haste',
    statsTitle: '+118 Critical Strike and +39 Haste',
  },
  213485: {
    id: '213485',
    name: 'Versatile Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_1',
    quality: qualityThree,
    stats: '+147 Haste and +49 Versatility',
    statsTitle: '+147 Haste and +49 Versatility',
  },
  213484: {
    id: '213484',
    name: 'Versatile Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_1',
    quality: qualityTwo,
    stats: '132 Haste and +44 Versatility',
    statsTitle: '+132 Haste and +44 Versatility',
  },
  213483: {
    id: '213483',
    name: 'Versatile Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color1_1',
    quality: qualityOne,
    stats: '+118 Haste and +39 Versatility',
    statsTitle: '+118 Haste and +39 Versatility',
  },
  213458: {
    id: '213458',
    name: 'Masterful Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_1',
    quality: qualityThree,
    stats: '+147 Critical Strike and +49 Mastery',
    statsTitle: '+147 Critical Strike and +49 Mastery',
  },
  213457: {
    id: '213457',
    name: 'Masterful Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_1',
    quality: qualityTwo,
    stats: '+132 Critical Strike and +44 Mastery',
    statsTitle: '+132 Critical Strike and +44 Mastery',
  },
  213456: {
    id: '213456',
    name: 'Masterful Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_1',
    quality: qualityOne,
    stats: '+118 Critical Strike and +39 Mastery',
    statsTitle: '+118 Critical Strike and +39 Mastery',
  },
  213491: {
    id: '213491',
    name: 'Deadly Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_2',
    quality: qualityThree,
    stats: '+147 Mastery and +49 Critical Strike',
    statsTitle: '+147 Mastery and +49 Critical Strike',
  },
  213490: {
    id: '213490',
    name: 'Deadly Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_2',
    quality: qualityTwo,
    stats: '+132 Mastery and +44 Critical Strike',
    statsTitle: '+132 Mastery and +44 Critical Strike',
  },
  213489: {
    id: '213489',
    name: 'Deadly Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_2',
    quality: qualityOne,
    stats: '+118 Mastery and +39 Critical Strike',
    statsTitle: '+118 Mastery and +39 Critical Strike',
  },
  213470: {
    id: '213470',
    name: 'Quick Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_3',
    quality: qualityThree,
    stats: '+147 Versatility and +49 Haste',
    statsTitle: '+147 Versatility and +49 Haste',
  },
  213469: {
    id: '213469',
    name: 'Quick Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_3',
    quality: qualityTwo,
    stats: '+132 Versatility and +44 Haste',
    statsTitle: '+132 Versatility and +44 Haste',
  },
  213468: {
    id: '213468',
    name: 'Quick Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_3',
    quality: qualityOne,
    stats: '+118 Versatility and +39 Haste',
    statsTitle: '+118 Versatility and +39 Haste',
  },
  213473: {
    id: '213473',
    name: 'Masterful Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_1',
    quality: qualityThree,
    stats: '+147 Versatility and +49 Mastery',
    statsTitle: '+147 Versatility and +49 Mastery',
  },
  213472: {
    id: '213472',
    name: 'Masterful Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_1',
    quality: qualityTwo,
    stats: '+132 Versatility and +44 Mastery',
    statsTitle: '+132 Versatility and +44 Mastery',
  },
  213471: {
    id: '213471',
    name: 'Masterful Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_1',
    quality: qualityOne,
    stats: '+118 Versatility and +39 Mastery',
    statsTitle: '+118 Versatility and +39 Mastery',
  },
  228647: {
    id: '228647',
    name: "Seabed Leviathan's Citrine",
    ico: 'inv_siren_isle_singing_citrine_purple',
    quality: '',
    stats: '',
    statsTitle:
      'Equip: Grants 4854023.782 / 8211.35 Stamina and increases your size slightly. In addition, being above 80% health causes attackers to take 8838.78 Frost damage.',
  },
  213497: {
    id: '213497',
    name: 'Versatile Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_1',
    quality: qualityThree,
    stats: '+147 Mastery and +49 Versatility',
    statsTitle: '+147 Mastery and +49 Versatility',
  },
  213496: {
    id: '213496',
    name: 'Versatile Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_1',
    quality: qualityTwo,
    stats: '+132 Mastery and +44 Versatility',
    statsTitle: '+132 Mastery and +44 Versatility',
  },
  213495: {
    id: '213495',
    name: 'Versatile Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color2_1',
    quality: qualityOne,
    stats: '+118 Mastery and +39 Versatility',
    statsTitle: '+118 Mastery and +39 Versatility',
  },
  213461: {
    id: '213461',
    name: 'Versatile Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_2',
    quality: qualityThree,
    stats: '+147 Critical Strike and +49 Versatility',
    statsTitle: '+147 Critical Strike and +49 Versatility',
  },
  213460: {
    id: '213460',
    name: 'Versatile Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_2',
    quality: qualityTwo,
    stats: '+132 Critical Strike and +44 Versatility',
    statsTitle: '+132 Critical Strike and +44 Versatility',
  },
  213459: {
    id: '213459',
    name: 'Versatile Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color4_2',
    quality: qualityOne,
    stats: '+118 Critical Strike and +39 Versatility',
    statsTitle: '+118 Critical Strike and +39 Versatility',
  },

  213467: {
    id: '213467',
    name: 'Deadly Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_2',
    quality: qualityThree,
    stats: '+147 Versatility and +49 Critical Strike',
    statsTitle: '+147 Versatility and +49 Critical Strike',
  },
  213466: {
    id: '213466',
    name: 'Deadly Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_2',
    quality: qualityTwo,
    stats: '+132 Versatility and +44 Critical Strike',
    statsTitle: '+132 Versatility and +44 Critical Strike',
  },
  213465: {
    id: '213465',
    name: 'Deadly Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem-hybrid_color5_2',
    quality: qualityOne,
    stats: '+118 Versatility and +39 Critical Strike',
    statsTitle: '+118 Versatility and +39 Critical Strike',
  },
  213740: {
    id: '213740',
    name: 'Insightful Blasphemite',
    ico: 'inv_misc_metagem_b',
    quality: qualityThree,
    stats:
      ' +181 Primary Stat and +1% Maximum Mana per unique Algari gem color',
    statsTitle:
      'Unique-Equipped: Algari Diamond (1). +181 Primary Stat and +1% Maximum Mana per unique Algari gem color',
  },
  213739: {
    id: '213739',
    name: 'Insightful Blasphemite',
    ico: 'inv_misc_metagem_b',
    quality: qualityTwo,
    stats: '+159 Primary Stat and +1% Maximum Mana per unique Algari gem color',
    statsTitle:
      '+159 Primary Stat and +1% Maximum Mana per unique Algari gem color',
  },
  213738: {
    id: '213738',
    name: 'Insightful Blasphemite',
    ico: 'inv_misc_metagem_b',
    quality: qualityOne,
    stats: '+136 Primary Stat and +1% Maximum Mana per unique Algari gem color',
    statsTitle:
      '+136 Primary Stat and +1% Maximum Mana per unique Algari gem color',
  },
  213488: {
    id: '213488',
    name: 'Quick Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem_color2',
    quality: qualityThree,
    stats: '+176 Haste',
    statsTitle: '+176 Haste',
  },
  213487: {
    id: '213487',
    name: 'Quick Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem_color2',
    quality: qualityTwo,
    stats: '+159 Haste',
    statsTitle: '+159 Haste',
  },
  213486: {
    id: '213486',
    name: 'Quick Emerald',
    ico: 'inv_jewelcrafting_cut-standart-gem_color2',
    quality: qualityOne,
    stats: '+141 Haste',
    statsTitle: '+141 Haste',
  },
  217115: {
    id: '217115',
    name: 'Cubic Blasphemia',
    ico: 'inv_stone_01',
    quality: qualityThree,
    stats: '+181 Primary Stat',
    statsTitle: '+181 Primary Stat',
  },
  217114: {
    id: '217114',
    name: 'Cubic Blasphemia',
    ico: 'inv_stone_01',
    quality: qualityTwo,
    stats: '+159 Primary Stat',
    statsTitle: '+159 Primary Stat',
  },
  217113: {
    id: '217113',
    name: 'Cubic Blasphemia',
    ico: 'inv_stone_01',
    quality: qualityOne,
    stats: '+136 Primary Stat',
    statsTitle: '+136 Primary Stat',
  },

  213500: {
    id: '213500',
    name: 'Masterful Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem_color1',
    quality: qualityThree,
    stats: '+176 Mastery',
    statsTitle: '+176 Mastery',
  },
  213499: {
    id: '213499',
    name: 'Masterful Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem_color1',
    quality: qualityTwo,
    stats: '+159 Mastery',
    statsTitle: '+159 Mastery',
  },
  213498: {
    id: '213498',
    name: 'Masterful Onyx',
    ico: 'inv_jewelcrafting_cut-standart-gem_color1',
    quality: qualityOne,
    stats: '+141 Mastery',
    statsTitle: '+141 Mastery',
  },
  213464: {
    id: '213464',
    name: 'Deadly Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem_color5',
    quality: qualityThree,
    stats: '+176 Critical Strike',
    statsTitle: '+176 Critical Strike',
  },
  213463: {
    id: '213463',
    name: 'Deadly Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem_color5',
    quality: qualityTwo,
    stats: '+159 Critical Strike',
    statsTitle: '+159 Critical Strike',
  },
  213462: {
    id: '213462',
    name: 'Deadly Ruby',
    ico: 'inv_jewelcrafting_cut-standart-gem_color5',
    quality: qualityOne,
    stats: '+141 Critical Strike',
    statsTitle: '+141 Critical Strike',
  },
  213476: {
    id: '213476',
    name: 'Versatile Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem_color3',
    quality: qualityThree,
    stats: '+176 Versatility',
    statsTitle: '+176 Versatility',
  },
  213475: {
    id: '213475',
    name: 'Versatile Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem_color3',
    quality: qualityTwo,
    stats: '+159 Versatility',
    statsTitle: '+159 Versatility',
  },
  213474: {
    id: '213474',
    name: 'Versatile Sapphire',
    ico: 'inv_jewelcrafting_cut-standart-gem_color3',
    quality: qualityOne,
    stats: '+141 Versatility',
    statsTitle: '+141 Versatility',
  },
}

export const ENCHANTS_DATA = {
  3368: {
    id: '3368',
    displayName: 'Rune of the Fallen Crusader',
    spellId: '53344',
    spellIcon: 'spell_holy_retributionaura',
    tokenizedName: 'rune_of_the_fallen_crusader',
  },
  3370: {
    id: 3370,
    displayName: 'Rune of Razorice',
    spellId: 53343,
    spellIcon: 'spell_frost_frostarmor',
    tokenizedName: 'rune_of_razorice',
  },
  3847: {
    id: 3847,
    displayName: 'Rune of the Stoneskin Gargoyle',
    spellId: 62158,
    spellIcon: 'inv_sword_130',
    tokenizedName: 'rune_of_the_stoneskin_gargoyle',
  },
  6241: {
    id: 6241,
    displayName: 'Rune of Sanguination',
    spellId: 326805,
    spellIcon: 'ability_argus_deathfog',
    tokenizedName: 'rune_of_sanguination',
  },
  6242: {
    id: 6242,
    displayName: 'Rune of Spellwarding',
    spellId: 326855,
    spellIcon: 'spell_fire_twilightfireward',
    tokenizedName: 'rune_of_spellwarding',
  },
  6244: {
    id: 6244,
    displayName: 'Rune of Unending Thirst',
    spellId: 326977,
    spellIcon: 'spell_nzinsanity_bloodthirst',
    tokenizedName: 'rune_of_unending_thirst',
  },
  6245: {
    id: 6245,
    displayName: 'Rune of the Apocalypse',
    spellId: 327082,
    spellIcon: 'spell_deathknight_thrash_ghoul',
    tokenizedName: 'rune_of_the_apocalypse',
  },

  7329: {
    id: 7329,
    displayName: '130 Crit',
    spellId: 445358,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223657,
    itemName: 'Glimmering Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'glimmering_critical_strike_1',
    stats: [{type: 'crit', amount: 130}],
  },
  7330: {
    id: 7330,
    displayName: '160 Crit',
    spellId: 445358,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223658,
    itemName: 'Glimmering Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'glimmering_critical_strike_2',
    stats: [{type: 'crit', amount: 160}],
  },
  7331: {
    id: 7331,
    displayName: '190 Crit',
    spellId: 445358,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223659,
    itemName: 'Glimmering Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'glimmering_critical_strike_3',
    stats: [{type: 'crit', amount: 190}],
  },
  7332: {
    id: 7332,
    displayName: '220 Crit',
    spellId: 445387,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223660,
    itemName: 'Radiant Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'radiant_critical_strike_1',
    stats: [{type: 'crit', amount: 220}],
  },
  7333: {
    id: 7333,
    displayName: '265 Crit',
    spellId: 445387,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223661,
    itemName: 'Radiant Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'radiant_critical_strike_2',
    stats: [{type: 'crit', amount: 265}],
  },
  7334: {
    id: 7334,
    displayName: '315 Crit',
    spellId: 445387,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223662,
    itemName: 'Radiant Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'radiant_critical_strike_3',
    stats: [{type: 'crit', amount: 315}],
  },
  7335: {
    id: 7335,
    displayName: '130 Haste',
    spellId: 455488,
    spellIcon: 'ui_profession_enchanting',
    itemId: 225652,
    itemName: 'Glimmering Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'glimmering_haste_1',
    stats: [{type: 'haste', amount: 130}],
  },
  7336: {
    id: 7336,
    displayName: '160 Haste',
    spellId: 445384,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223664,
    itemName: 'Glimmering Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'glimmering_haste_2',
    stats: [{type: 'haste', amount: 160}],
  },
  7337: {
    id: 7337,
    displayName: '190 Haste',
    spellId: 445384,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223665,
    itemName: 'Glimmering Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'glimmering_haste_3',
    stats: [{type: 'haste', amount: 190}],
  },
  7338: {
    id: 7338,
    displayName: '220 Haste',
    spellId: 445320,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223672,
    itemName: 'Radiant Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'radiant_haste_1',
    stats: [{type: 'haste', amount: 220}],
  },
  7339: {
    id: 7339,
    displayName: '265 Haste',
    spellId: 445320,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223673,
    itemName: 'Radiant Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'radiant_haste_2',
    stats: [{type: 'haste', amount: 265}],
  },
  7340: {
    id: 7340,
    displayName: '315 Haste',
    spellId: 445320,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223674,
    itemName: 'Radiant Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'radiant_haste_3',
    stats: [{type: 'haste', amount: 315}],
  },
  7341: {
    id: 7341,
    displayName: '130 Mast',
    spellId: 445381,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223666,
    itemName: 'Glimmering Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'glimmering_mastery_1',
    stats: [{type: 'mastery', amount: 130}],
  },
  7342: {
    id: 7342,
    displayName: '160 Mast',
    spellId: 445381,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223667,
    itemName: 'Glimmering Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'glimmering_mastery_2',
    stats: [{type: 'mastery', amount: 160}],
  },
  7343: {
    id: 7343,
    displayName: '190 Mast',
    spellId: 445381,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223668,
    itemName: 'Glimmering Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'glimmering_mastery_3',
    stats: [{type: 'mastery', amount: 190}],
  },
  7344: {
    id: 7344,
    displayName: '220 Mast',
    spellId: 445375,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223675,
    itemName: 'Radiant Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'radiant_mastery_1',
    stats: [{type: 'mastery', amount: 220}],
  },
  7345: {
    id: 7345,
    displayName: '265 Mast',
    spellId: 445375,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223676,
    itemName: 'Radiant Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'radiant_mastery_2',
    stats: [{type: 'mastery', amount: 265}],
  },
  7346: {
    id: 7346,
    displayName: '315 Mast',
    spellId: 445375,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223677,
    itemName: 'Radiant Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'radiant_mastery_3',
    stats: [{type: 'mastery', amount: 315}],
  },
  7347: {
    id: 7347,
    displayName: '130 Vers',
    spellId: 445340,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223669,
    itemName: 'Glimmering Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'glimmering_versatility_1',
    stats: [{type: 'vers', amount: 130}],
  },
  7348: {
    id: 7348,
    displayName: '160 Vers',
    spellId: 445340,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223670,
    itemName: 'Glimmering Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'glimmering_versatility_2',
    stats: [{type: 'vers', amount: 160}],
  },
  7349: {
    id: 7349,
    displayName: '190 Vers',
    spellId: 445340,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223671,
    itemName: 'Glimmering Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'glimmering_versatility_3',
    stats: [{type: 'vers', amount: 190}],
  },
  7350: {
    id: 7350,
    displayName: '220 Vers',
    spellId: 445349,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223678,
    itemName: 'Radiant Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'radiant_versatility_1',
    stats: [{type: 'vers', amount: 220}],
  },
  7351: {
    id: 7351,
    displayName: '265 Vers',
    spellId: 445349,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223679,
    itemName: 'Radiant Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'radiant_versatility_2',
    stats: [{type: 'vers', amount: 265}],
  },
  7352: {
    id: 7352,
    displayName: '315 Vers',
    spellId: 445349,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223680,
    itemName: 'Radiant Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'radiant_versatility_3',
    stats: [{type: 'vers', amount: 315}],
  },
  7353: {
    id: 7353,
    baseDisplayName: "Stormrider's Agi",
    displayName: "Stormrider's Agi 1",
    spellId: 445353,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223681,
    itemName: "Stormrider's Agility",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'stormriders_agility_1',
    stats: [
      {type: 'agi', amount: 360},
      {type: 'runspeed', amount: 180},
    ],
  },
  7354: {
    id: 7354,
    baseDisplayName: "Stormrider's Agi",
    displayName: "Stormrider's Agi 2",
    spellId: 445353,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223682,
    itemName: "Stormrider's Agility",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'stormriders_agility_2',
    stats: [
      {type: 'agi', amount: 440},
      {type: 'runspeed', amount: 215},
    ],
  },
  7355: {
    id: 7355,
    baseDisplayName: "Stormrider's Agi",
    displayName: "Stormrider's Agi 3",
    spellId: 445353,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223683,
    itemName: "Stormrider's Agility",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'stormriders_agility_3',
    stats: [
      {type: 'agi', amount: 520},
      {type: 'runspeed', amount: 250},
    ],
  },
  7356: {
    id: 7356,
    baseDisplayName: "Council's Int",
    displayName: "Council's Int 1",
    spellId: 445322,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223684,
    itemName: "Council's Intellect",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'councils_intellect_1',
    stats: [{type: 'int', amount: 360}],
    spellEffects: [449436],
  },
  7357: {
    id: 7357,
    baseDisplayName: "Council's Int",
    displayName: "Council's Int 2",
    spellId: 445322,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223685,
    itemName: "Council's Intellect",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'councils_intellect_2',
    stats: [{type: 'int', amount: 440}],
    spellEffects: [449437],
  },
  7358: {
    id: 7358,
    baseDisplayName: "Council's Int",
    displayName: "Council's Int 3",
    spellId: 445322,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223686,
    itemName: "Council's Intellect",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'councils_intellect_3',
    stats: [{type: 'int', amount: 520}],
    spellEffects: [449438],
  },
  7359: {
    id: 7359,
    baseDisplayName: "Oathsworn's Str",
    displayName: "Oathsworn's Str 1",
    spellId: 445321,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223687,
    itemName: "Oathsworn's Strength",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'oathsworns_strength_1',
    stats: [
      {type: 'str', amount: 365},
      {type: 'sta', amount: 185},
    ],
  },
  7360: {
    id: 7360,
    baseDisplayName: "Oathsworn's Str",
    displayName: "Oathsworn's Str 2",
    spellId: 445321,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223688,
    itemName: "Oathsworn's Strength",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'oathsworns_strength_2',
    stats: [
      {type: 'str', amount: 440},
      {type: 'sta', amount: 225},
    ],
  },
  7361: {
    id: 7361,
    baseDisplayName: "Oathsworn's Str",
    displayName: "Oathsworn's Str 3",
    spellId: 445321,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223689,
    itemName: "Oathsworn's Strength",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'oathsworns_strength_3',
    stats: [
      {type: 'str', amount: 520},
      {type: 'sta', amount: 265},
    ],
  },
  7362: {
    id: 7362,
    baseDisplayName: 'Crystalline Radiance',
    displayName: 'Crystalline Radiance 1',
    spellId: 445333,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223690,
    itemName: 'Crystalline Radiance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'crystalline_radiance_1',
    stats: [{type: 'stragiint', amount: 520}],
  },
  7363: {
    id: 7363,
    baseDisplayName: 'Crystalline Radiance',
    displayName: 'Crystalline Radiance 2',
    spellId: 445333,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223691,
    itemName: 'Crystalline Radiance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'crystalline_radiance_2',
    stats: [{type: 'stragiint', amount: 630}],
  },
  7364: {
    id: 7364,
    baseDisplayName: 'Crystalline Radiance',
    displayName: 'Crystalline Radiance 3',
    spellId: 445333,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223692,
    itemName: 'Crystalline Radiance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'crystalline_radiance_3',
    stats: [{type: 'stragiint', amount: 745}],
  },
  7380: {
    id: 7380,
    displayName: '380 Avoidance',
    spellId: 445392,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223708,
    itemName: 'Whisper of Armored Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'whisper_of_armored_avoidance_1',
    stats: [{type: 'avoidance', amount: 380}],
  },
  7381: {
    id: 7381,
    displayName: '545 Avoidance',
    spellId: 445392,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223709,
    itemName: 'Whisper of Armored Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'whisper_of_armored_avoidance_2',
    stats: [{type: 'avoidance', amount: 545}],
  },
  7382: {
    id: 7382,
    displayName: '710 Avoidance',
    spellId: 445392,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223710,
    itemName: 'Whisper of Armored Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'whisper_of_armored_avoidance_3',
    stats: [{type: 'avoidance', amount: 710}],
  },
  7383: {
    id: 7383,
    displayName: '760 Avoidance',
    spellId: 445334,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223711,
    itemName: 'Chant of Armored Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'chant_of_armored_avoidance_1',
    stats: [{type: 'avoidance', amount: 760}],
  },
  7384: {
    id: 7384,
    displayName: '925 Avoidance',
    spellId: 445334,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223712,
    itemName: 'Chant of Armored Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'chant_of_armored_avoidance_2',
    stats: [{type: 'avoidance', amount: 925}],
  },
  7385: {
    id: 7385,
    displayName: '1,090 Avoidance',
    spellId: 445334,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223713,
    itemName: 'Chant of Armored Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'chant_of_armored_avoidance_3',
    stats: [{type: 'avoidance', amount: 1090}],
  },
  7386: {
    id: 7386,
    displayName: '715 Leech',
    spellId: 445374,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223714,
    itemName: 'Whisper of Armored Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'whisper_of_armored_leech_1',
    stats: [{type: 'leech', amount: 715}],
  },
  7387: {
    id: 7387,
    displayName: '1,020 Leech',
    spellId: 445374,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223715,
    itemName: 'Whisper of Armored Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'whisper_of_armored_leech_2',
    stats: [{type: 'leech', amount: 1020}],
  },
  7388: {
    id: 7388,
    displayName: '1,325 Leech',
    spellId: 445374,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223716,
    itemName: 'Whisper of Armored Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'whisper_of_armored_leech_3',
    stats: [{type: 'leech', amount: 1325}],
  },
  7389: {
    id: 7389,
    displayName: '1,425 Leech',
    spellId: 445325,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223717,
    itemName: 'Chant of Armored Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'chant_of_armored_leech_1',
    stats: [{type: 'leech', amount: 1425}],
  },
  7390: {
    id: 7390,
    displayName: '1,735 Leech',
    spellId: 445325,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223718,
    itemName: 'Chant of Armored Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'chant_of_armored_leech_2',
    stats: [{type: 'leech', amount: 1735}],
  },
  7391: {
    id: 7391,
    displayName: '2,040 Leech',
    spellId: 445325,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223719,
    itemName: 'Chant of Armored Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'chant_of_armored_leech_3',
    stats: [{type: 'leech', amount: 2040}],
  },
  7392: {
    id: 7392,
    displayName: '350 Speed',
    spellId: 445376,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223720,
    itemName: 'Whisper of Armored Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'whisper_of_armored_speed_1',
    stats: [{type: 'runspeed', amount: 350}],
  },
  7393: {
    id: 7393,
    displayName: '500 Speed',
    spellId: 445376,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223721,
    itemName: 'Whisper of Armored Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'whisper_of_armored_speed_2',
    stats: [{type: 'runspeed', amount: 500}],
  },
  7394: {
    id: 7394,
    displayName: '650 Speed',
    spellId: 445376,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223722,
    itemName: 'Whisper of Armored Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'whisper_of_armored_speed_3',
    stats: [{type: 'runspeed', amount: 650}],
  },
  7395: {
    id: 7395,
    displayName: '700 Speed',
    spellId: 445330,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223723,
    itemName: 'Chant of Armored Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'chant_of_armored_speed_1',
    stats: [{type: 'runspeed', amount: 700}],
  },
  7396: {
    id: 7396,
    displayName: '850 Speed',
    spellId: 445330,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223724,
    itemName: 'Chant of Armored Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'chant_of_armored_speed_2',
    stats: [{type: 'runspeed', amount: 850}],
  },
  7397: {
    id: 7397,
    displayName: '1,000 Speed',
    spellId: 445330,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223725,
    itemName: 'Chant of Armored Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'chant_of_armored_speed_3',
    stats: [{type: 'runspeed', amount: 1000}],
  },
  7398: {
    id: 7398,
    displayName: '190 Avoidance',
    spellId: 445344,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223726,
    itemName: 'Whisper of Silken Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'whisper_of_silken_avoidance_1',
    stats: [{type: 'avoidance', amount: 190}],
  },
  7399: {
    id: 7399,
    displayName: '270 Avoidance',
    spellId: 445344,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223727,
    itemName: 'Whisper of Silken Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'whisper_of_silken_avoidance_2',
    stats: [{type: 'avoidance', amount: 270}],
  },
  7400: {
    id: 7400,
    displayName: '355 Avoidance',
    spellId: 445344,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223728,
    itemName: 'Whisper of Silken Avoidance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'whisper_of_silken_avoidance_3',
    stats: [{type: 'avoidance', amount: 355}],
  },
  7401: {
    id: 7401,
    baseDisplayName: 'Chant of Winged Grace',
    displayName: 'Chant of Winged Grace 1',
    spellId: 445386,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223729,
    itemName: 'Chant of Winged Grace',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'chant_of_winged_grace_1',
    stats: [{type: 'avoidance', amount: 380}],
    spellEffects: [449735],
  },
  7402: {
    id: 7402,
    baseDisplayName: 'Chant of Winged Grace',
    displayName: 'Chant of Winged Grace 2',
    spellId: 445386,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223730,
    itemName: 'Chant of Winged Grace',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'chant_of_winged_grace_2',
    stats: [{type: 'avoidance', amount: 465}],
    spellEffects: [449736],
  },
  7403: {
    id: 7403,
    baseDisplayName: 'Chant of Winged Grace',
    displayName: 'Chant of Winged Grace 3',
    spellId: 445386,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223731,
    itemName: 'Chant of Winged Grace',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'chant_of_winged_grace_3',
    stats: [{type: 'avoidance', amount: 545}],
    spellEffects: [449737],
  },
  7404: {
    id: 7404,
    displayName: '355 Leech',
    spellId: 445348,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223732,
    itemName: 'Whisper of Silken Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'whisper_of_silken_leech_1',
    stats: [{type: 'leech', amount: 355}],
  },
  7405: {
    id: 7405,
    displayName: '510 Leech',
    spellId: 445348,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223733,
    itemName: 'Whisper of Silken Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'whisper_of_silken_leech_2',
    stats: [{type: 'leech', amount: 510}],
  },
  7406: {
    id: 7406,
    displayName: '665 Leech',
    spellId: 445348,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223734,
    itemName: 'Whisper of Silken Leech',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'whisper_of_silken_leech_3',
    stats: [{type: 'leech', amount: 665}],
  },
  7407: {
    id: 7407,
    baseDisplayName: 'Chant of Leeching Fangs',
    displayName: 'Chant of Leeching Fangs 1',
    spellId: 445393,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223735,
    itemName: 'Chant of Leeching Fangs',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'chant_of_leeching_fangs_1',
    stats: [{type: 'leech', amount: 715}],
    spellEffects: [449739],
  },
  7408: {
    id: 7408,
    baseDisplayName: 'Chant of Leeching Fangs',
    displayName: 'Chant of Leeching Fangs 2',
    spellId: 445393,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223736,
    itemName: 'Chant of Leeching Fangs',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'chant_of_leeching_fangs_2',
    stats: [{type: 'leech', amount: 865}],
    spellEffects: [449740],
  },
  7409: {
    id: 7409,
    baseDisplayName: 'Chant of Leeching Fangs',
    displayName: 'Chant of Leeching Fangs 3',
    spellId: 445393,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223737,
    itemName: 'Chant of Leeching Fangs',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'chant_of_leeching_fangs_3',
    stats: [{type: 'leech', amount: 1020}],
    spellEffects: [449741],
  },
  7410: {
    id: 7410,
    displayName: '85 Speed',
    spellId: 445373,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223738,
    itemName: 'Whisper of Silken Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'whisper_of_silken_speed_1',
    stats: [{type: 'runspeed', amount: 85}],
  },
  7411: {
    id: 7411,
    displayName: '125 Speed',
    spellId: 445373,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223739,
    itemName: 'Whisper of Silken Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'whisper_of_silken_speed_2',
    stats: [{type: 'runspeed', amount: 125}],
  },
  7412: {
    id: 7412,
    displayName: '160 Speed',
    spellId: 445373,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223740,
    itemName: 'Whisper of Silken Speed',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'whisper_of_silken_speed_3',
    stats: [{type: 'runspeed', amount: 160}],
  },
  7413: {
    id: 7413,
    baseDisplayName: 'Chant of Burrowing Rapidity',
    displayName: 'Chant of Burrowing Rapidity 1',
    spellId: 445389,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223798,
    itemName: 'Chant of Burrowing Rapidity',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'chant_of_burrowing_rapidity_1',
    stats: [{type: 'runspeed', amount: 175}],
    spellEffects: [449752],
  },
  7414: {
    id: 7414,
    baseDisplayName: 'Chant of Burrowing Rapidity',
    displayName: 'Chant of Burrowing Rapidity 2',
    spellId: 445389,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223799,
    itemName: 'Chant of Burrowing Rapidity',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'chant_of_burrowing_rapidity_2',
    stats: [{type: 'runspeed', amount: 210}],
    spellEffects: [449743],
  },
  7415: {
    id: 7415,
    baseDisplayName: 'Chant of Burrowing Rapidity',
    displayName: 'Chant of Burrowing Rapidity 3',
    spellId: 445389,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223800,
    itemName: 'Chant of Burrowing Rapidity',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'chant_of_burrowing_rapidity_3',
    stats: [{type: 'runspeed', amount: 250}],
    spellEffects: [449744],
  },
  7416: {
    id: 7416,
    baseDisplayName: "Scout's March",
    displayName: "Scout's March 1",
    spellId: 445368,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223651,
    itemName: "Scout's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'scouts_march_1',
    stats: [{type: 'runspeed', amount: 175}],
  },
  7417: {
    id: 7417,
    baseDisplayName: "Scout's March",
    displayName: "Scout's March 2",
    spellId: 445368,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223652,
    itemName: "Scout's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'scouts_march_2',
    stats: [{type: 'runspeed', amount: 215}],
  },
  7418: {
    id: 7418,
    baseDisplayName: "Scout's March",
    displayName: "Scout's March 3",
    spellId: 445368,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223653,
    itemName: "Scout's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'scouts_march_3',
    stats: [{type: 'runspeed', amount: 250}],
  },
  7419: {
    id: 7419,
    baseDisplayName: "Cavalry's March",
    displayName: "Cavalry's March 1",
    spellId: 445335,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223618,
    itemName: "Cavalry's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'cavalrys_march_1',
  },
  7420: {
    id: 7420,
    baseDisplayName: "Cavalry's March",
    displayName: "Cavalry's March 2",
    spellId: 445335,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223649,
    itemName: "Cavalry's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'cavalrys_march_2',
  },
  7421: {
    id: 7421,
    baseDisplayName: "Cavalry's March",
    displayName: "Cavalry's March 3",
    spellId: 445335,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223650,
    itemName: "Cavalry's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'cavalrys_march_3',
  },
  7422: {
    id: 7422,
    baseDisplayName: "Defender's March",
    displayName: "Defender's March 1",
    spellId: 445396,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223654,
    itemName: "Defender's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'defenders_march_1',
    stats: [{type: 'sta', amount: 625}],
  },
  7423: {
    id: 7423,
    baseDisplayName: "Defender's March",
    displayName: "Defender's March 2",
    spellId: 445396,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223655,
    itemName: "Defender's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'defenders_march_2',
    stats: [{type: 'sta', amount: 760}],
  },
  7424: {
    id: 7424,
    baseDisplayName: "Defender's March",
    displayName: "Defender's March 3",
    spellId: 445396,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223656,
    itemName: "Defender's March",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'defenders_march_3',
    stats: [{type: 'sta', amount: 895}],
  },
  7425: {
    id: 7425,
    baseDisplayName: 'Illusory Adornment: Crystal',
    displayName: 'Illusory Adornment: Crystal 1',
    spellId: 445327,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223746,
    itemName: 'Illusory Adornment: Crystal',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'illusory_adornment_crystal_1',
  },
  7426: {
    id: 7426,
    baseDisplayName: 'Illusory Adornment: Crystal',
    displayName: 'Illusory Adornment: Crystal 2',
    spellId: 445327,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223745,
    itemName: 'Illusory Adornment: Crystal',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'illusory_adornment_crystal_2',
  },
  7427: {
    id: 7427,
    baseDisplayName: 'Illusory Adornment: Crystal',
    displayName: 'Illusory Adornment: Crystal 3',
    spellId: 445327,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223747,
    itemName: 'Illusory Adornment: Crystal',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'illusory_adornment_crystal_3',
  },
  7428: {
    id: 7428,
    baseDisplayName: 'Illusory Adornment: Radiance',
    displayName: 'Illusory Adornment: Radiance 1',
    spellId: 445401,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223748,
    itemName: 'Illusory Adornment: Radiance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'illusory_adornment_radiance_1',
  },
  7429: {
    id: 7429,
    baseDisplayName: 'Illusory Adornment: Radiance',
    displayName: 'Illusory Adornment: Radiance 2',
    spellId: 445401,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223749,
    itemName: 'Illusory Adornment: Radiance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'illusory_adornment_radiance_2',
  },
  7430: {
    id: 7430,
    baseDisplayName: 'Illusory Adornment: Radiance',
    displayName: 'Illusory Adornment: Radiance 3',
    spellId: 445401,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223750,
    itemName: 'Illusory Adornment: Radiance',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'illusory_adornment_radiance_3',
  },
  7431: {
    id: 7431,
    baseDisplayName: 'Illusory Adornment: Runes',
    displayName: 'Illusory Adornment: Runes 1',
    spellId: 445360,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223751,
    itemName: 'Illusory Adornment: Runes',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'illusory_adornment_runes_1',
  },
  7432: {
    id: 7432,
    baseDisplayName: 'Illusory Adornment: Runes',
    displayName: 'Illusory Adornment: Runes 2',
    spellId: 445360,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223752,
    itemName: 'Illusory Adornment: Runes',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'illusory_adornment_runes_2',
  },
  7433: {
    id: 7433,
    baseDisplayName: 'Illusory Adornment: Runes',
    displayName: 'Illusory Adornment: Runes 3',
    spellId: 445360,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223753,
    itemName: 'Illusory Adornment: Runes',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'illusory_adornment_runes_3',
  },
  7434: {
    id: 7434,
    baseDisplayName: 'Illusory Adornment: Shadow',
    displayName: 'Illusory Adornment: Shadow 1',
    spellId: 445337,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223754,
    itemName: 'Illusory Adornment: Shadow',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'illusory_adornment_shadow_1',
  },
  7435: {
    id: 7435,
    baseDisplayName: 'Illusory Adornment: Shadow',
    displayName: 'Illusory Adornment: Shadow 2',
    spellId: 445337,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223755,
    itemName: 'Illusory Adornment: Shadow',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'illusory_adornment_shadow_2',
  },
  7436: {
    id: 7436,
    baseDisplayName: 'Illusory Adornment: Shadow',
    displayName: 'Illusory Adornment: Shadow 3',
    spellId: 445337,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223756,
    itemName: 'Illusory Adornment: Shadow',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'illusory_adornment_shadow_3',
  },
  7437: {
    id: 7437,
    baseDisplayName: "Council's Guile",
    displayName: "Council's Guile 1",
    spellId: 445379,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223757,
    itemName: "Council's Guile",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'councils_guile_1',
  },
  7438: {
    id: 7438,
    baseDisplayName: "Council's Guile",
    displayName: "Council's Guile 2",
    spellId: 445379,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223758,
    itemName: "Council's Guile",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'councils_guile_2',
  },
  7439: {
    id: 7439,
    baseDisplayName: "Council's Guile",
    displayName: "Council's Guile 3",
    spellId: 445379,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223759,
    itemName: "Council's Guile",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'councils_guile_3',
  },
  7440: {
    id: 7440,
    baseDisplayName: "Stormrider's Fury",
    displayName: "Stormrider's Fury 1",
    spellId: 445317,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223760,
    itemName: "Stormrider's Fury",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'stormriders_fury_1',
  },
  7441: {
    id: 7441,
    baseDisplayName: "Stormrider's Fury",
    displayName: "Stormrider's Fury 2",
    spellId: 445317,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223761,
    itemName: "Stormrider's Fury",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'stormriders_fury_2',
  },
  7442: {
    id: 7442,
    baseDisplayName: "Stormrider's Fury",
    displayName: "Stormrider's Fury 3",
    spellId: 445317,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223762,
    itemName: "Stormrider's Fury",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'stormriders_fury_3',
  },
  7443: {
    id: 7443,
    baseDisplayName: 'Stonebound Artistry',
    displayName: 'Stonebound Artistry 1',
    spellId: 445385,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223763,
    itemName: 'Stonebound Artistry',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'stonebound_artistry_1',
  },
  7444: {
    id: 7444,
    baseDisplayName: 'Stonebound Artistry',
    displayName: 'Stonebound Artistry 2',
    spellId: 445385,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223764,
    itemName: 'Stonebound Artistry',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'stonebound_artistry_2',
  },
  7445: {
    id: 7445,
    baseDisplayName: 'Stonebound Artistry',
    displayName: 'Stonebound Artistry 3',
    spellId: 445385,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223765,
    itemName: 'Stonebound Artistry',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'stonebound_artistry_3',
  },
  7446: {
    id: 7446,
    baseDisplayName: "Oathsworn's Tenacity",
    displayName: "Oathsworn's Tenacity 1",
    spellId: 445351,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223766,
    itemName: "Oathsworn's Tenacity",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'oathsworns_tenacity_1',
  },
  7447: {
    id: 7447,
    baseDisplayName: "Oathsworn's Tenacity",
    displayName: "Oathsworn's Tenacity 2",
    spellId: 445351,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223767,
    itemName: "Oathsworn's Tenacity",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'oathsworns_tenacity_2',
  },
  7448: {
    id: 7448,
    baseDisplayName: "Oathsworn's Tenacity",
    displayName: "Oathsworn's Tenacity 3",
    spellId: 445351,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223768,
    itemName: "Oathsworn's Tenacity",
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'oathsworns_tenacity_3',
  },
  7449: {
    id: 7449,
    baseDisplayName: 'Authority of Air',
    displayName: 'Authority of Air 1',
    spellId: 445331,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223773,
    itemName: 'Authority of Air',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'authority_of_air_1',
  },
  7450: {
    id: 7450,
    baseDisplayName: 'Authority of Air',
    displayName: 'Authority of Air 2',
    spellId: 445331,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223774,
    itemName: 'Authority of Air',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'authority_of_air_2',
  },
  7451: {
    id: 7451,
    baseDisplayName: 'Authority of Air',
    displayName: 'Authority of Air 3',
    spellId: 445331,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223775,
    itemName: 'Authority of Air',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'authority_of_air_3',
  },
  7452: {
    id: 7452,
    baseDisplayName: 'Authority of Fiery Resolve',
    displayName: 'Authority of Fiery Resolve 1',
    spellId: 445403,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223776,
    itemName: 'Authority of Fiery Resolve',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'authority_of_fiery_resolve_1',
  },
  7453: {
    id: 7453,
    baseDisplayName: 'Authority of Fiery Resolve',
    displayName: 'Authority of Fiery Resolve 2',
    spellId: 445403,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223777,
    itemName: 'Authority of Fiery Resolve',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'authority_of_fiery_resolve_2',
  },
  7454: {
    id: 7454,
    baseDisplayName: 'Authority of Fiery Resolve',
    displayName: 'Authority of Fiery Resolve 3',
    spellId: 445403,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223778,
    itemName: 'Authority of Fiery Resolve',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'authority_of_fiery_resolve_3',
  },
  7455: {
    id: 7455,
    baseDisplayName: 'Authority of Storms',
    displayName: 'Authority of Storms 1',
    spellId: 445336,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223770,
    itemName: 'Authority of Storms',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'authority_of_storms_1',
  },
  7456: {
    id: 7456,
    baseDisplayName: 'Authority of Storms',
    displayName: 'Authority of Storms 2',
    spellId: 445336,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223771,
    itemName: 'Authority of Storms',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'authority_of_storms_2',
  },
  7457: {
    id: 7457,
    baseDisplayName: 'Authority of Storms',
    displayName: 'Authority of Storms 3',
    spellId: 445336,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223772,
    itemName: 'Authority of Storms',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'authority_of_storms_3',
  },
  7458: {
    id: 7458,
    baseDisplayName: 'Authority of the Depths',
    displayName: 'Authority of the Depths 1',
    spellId: 445341,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223782,
    itemName: 'Authority of the Depths',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'authority_of_the_depths_1',
  },
  7459: {
    id: 7459,
    baseDisplayName: 'Authority of the Depths',
    displayName: 'Authority of the Depths 2',
    spellId: 445341,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223783,
    itemName: 'Authority of the Depths',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'authority_of_the_depths_2',
  },
  7460: {
    id: 7460,
    baseDisplayName: 'Authority of the Depths',
    displayName: 'Authority of the Depths 3',
    spellId: 445341,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223784,
    itemName: 'Authority of the Depths',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'authority_of_the_depths_3',
  },
  7461: {
    id: 7461,
    baseDisplayName: 'Authority of Radiant Power',
    displayName: 'Authority of Radiant Power 1',
    spellId: 445339,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223779,
    itemName: 'Authority of Radiant Power',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'authority_of_radiant_power_1',
  },
  7462: {
    id: 7462,
    baseDisplayName: 'Authority of Radiant Power',
    displayName: 'Authority of Radiant Power 2',
    spellId: 445339,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223780,
    itemName: 'Authority of Radiant Power',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'authority_of_radiant_power_2',
  },
  7463: {
    id: 7463,
    baseDisplayName: 'Authority of Radiant Power',
    displayName: 'Authority of Radiant Power 3',
    spellId: 445339,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223781,
    itemName: 'Authority of Radiant Power',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'authority_of_radiant_power_3',
  },
  7468: {
    id: 7468,
    baseDisplayName: 'Cursed Crit',
    displayName: 'Cursed Crit 1',
    spellId: 445394,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223785,
    itemName: 'Cursed Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'cursed_critical_strike_1',
    spellEffects: [448337],
  },
  7469: {
    id: 7469,
    baseDisplayName: 'Cursed Crit',
    displayName: 'Cursed Crit 2',
    spellId: 445394,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223786,
    itemName: 'Cursed Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'cursed_critical_strike_2',
    spellEffects: [448338],
  },
  7470: {
    id: 7470,
    baseDisplayName: 'Cursed Crit',
    displayName: 'Cursed Crit 3',
    spellId: 445394,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223787,
    itemName: 'Cursed Critical Strike',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'cursed_critical_strike_3',
    spellEffects: [448339],
  },
  7471: {
    id: 7471,
    baseDisplayName: 'Cursed Haste',
    displayName: 'Cursed Haste 1',
    spellId: 445388,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223788,
    itemName: 'Cursed Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'cursed_haste_1',
    spellEffects: [448335],
  },
  7472: {
    id: 7472,
    baseDisplayName: 'Cursed Haste',
    displayName: 'Cursed Haste 2',
    spellId: 445388,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223789,
    itemName: 'Cursed Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'cursed_haste_2',
    spellEffects: [448336],
  },
  7473: {
    id: 7473,
    baseDisplayName: 'Cursed Haste',
    displayName: 'Cursed Haste 3',
    spellId: 445388,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223790,
    itemName: 'Cursed Haste',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'cursed_haste_3',
    spellEffects: [448334],
  },
  7474: {
    id: 7474,
    baseDisplayName: 'Cursed Vers',
    displayName: 'Cursed Vers 1',
    spellId: 445383,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223794,
    itemName: 'Cursed Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'cursed_versatility_1',
    spellEffects: [448326],
  },
  7475: {
    id: 7475,
    baseDisplayName: 'Cursed Vers',
    displayName: 'Cursed Vers 2',
    spellId: 445383,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223795,
    itemName: 'Cursed Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'cursed_versatility_2',
    spellEffects: [448327],
  },
  7476: {
    id: 7476,
    baseDisplayName: 'Cursed Vers',
    displayName: 'Cursed Vers 3',
    spellId: 445383,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223796,
    itemName: 'Cursed Versatility',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'cursed_versatility_3',
    spellEffects: [448328],
  },
  7477: {
    id: 7477,
    baseDisplayName: 'Cursed Mast',
    displayName: 'Cursed Mast 1',
    spellId: 445359,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223791,
    itemName: 'Cursed Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityOne,
    tokenizedName: 'cursed_mastery_1',
    spellEffects: [448331],
  },
  7478: {
    id: 7478,
    baseDisplayName: 'Cursed Mast',
    displayName: 'Cursed Mast 2',
    spellId: 445359,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223792,
    itemName: 'Cursed Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityTwo,
    tokenizedName: 'cursed_mastery_2',
    spellEffects: [448332],
  },
  7479: {
    id: 7479,
    baseDisplayName: 'Cursed Mast',
    displayName: 'Cursed Mast 3',
    spellId: 445359,
    spellIcon: 'ui_profession_enchanting',
    itemId: 223793,
    itemName: 'Cursed Mastery',
    itemIcon: 'inv_misc_enchantedscroll',
    craftingQuality: qualityThree,
    tokenizedName: 'cursed_mastery_3',
    spellEffects: [448333],
  },
  7505: {
    id: 7505,
    baseDisplayName: 'Earthen Delivery Drill',
    displayName: 'Earthen Delivery Drill 3',
    spellIcon: '',
    itemId: 221906,
    itemName: 'Tinker: Earthen Delivery Drill',
    itemIcon: 'inv_tinkermodule_yellow',
    itemLimitCategory: {
      id: 647,
      name: 'Earthen Delivery Drill',
      quantity: 1,
      flags: 1,
    },
    unique: 647,
    craftingQuality: qualityThree,
    tokenizedName: 'tinker_earthen_delivery_drill_3',
    slot: 'socket',
    socketType: 'TINKER',
  },
  7506: {
    id: 7506,
    baseDisplayName: 'Heartseeking Health Injector',
    displayName: 'Heartseeking Health Injector 3',
    spellIcon: '',
    itemId: 221910,
    itemName: 'Tinker: Heartseeking Health Injector',
    itemIcon: 'inv_tinkermodule_red',
    itemLimitCategory: {
      id: 648,
      name: 'Heartseeking Health Injector',
      quantity: 1,
      flags: 1,
    },
    unique: 648,
    craftingQuality: qualityThree,
    tokenizedName: 'tinker_heartseeking_health_injector_3',
    slot: 'socket',
    socketType: 'TINKER',
  },
  7522: {
    id: 7522,
    displayName: 'Refurbished Alarm-O-Turret',
    spellIcon: '',
    itemId: 225241,
    itemName: 'Turret',
    itemIcon: 'inv_10_engineering2_tinkermodules_color1',
    itemLimitCategory: {id: 569, name: 'Alarm-O-Turret', quantity: 1, flags: 1},
    unique: 569,
    tokenizedName: 'turret',
    slot: 'socket',
    socketType: 'TINKER',
  },
  7523: {
    id: 7523,
    displayName: 'Refurbished Plane Displacer',
    spellIcon: '',
    itemId: 225242,
    itemName: 'Refurbished Tinker: Plane Displacer',
    itemIcon: 'inv_10_engineering2_tinkermodules_color6',
    itemLimitCategory: {
      id: 573,
      name: 'Plane Displacer',
      quantity: 1,
      flags: 1,
    },
    unique: 573,
    tokenizedName: 'refurbished_tinker_plane_displacer',
    slot: 'socket',
    socketType: 'TINKER',
  },
  7524: {
    id: 7524,
    displayName: 'Refurbished Supercollide-O-Tron',
    spellIcon: '',
    itemId: 225243,
    itemName: 'Tron',
    itemIcon: 'inv_10_engineering2_tinkermodules_color5',
    itemLimitCategory: {
      id: 575,
      name: 'Supercollide-O-Tron',
      quantity: 1,
      flags: 1,
    },
    unique: 575,
    tokenizedName: 'tron',
    slot: 'socket',
    socketType: 'TINKER',
  },
  7525: {
    id: 7525,
    displayName: 'Refurbished Shadowflame Rockets',
    spellIcon: '',
    itemId: 225244,
    itemName: 'Refurbished Tinker: Shadowflame Rockets',
    itemIcon: 'inv_10_engineering2_tinkermodules_color3',
    itemLimitCategory: {
      id: 599,
      name: 'Shadowflame Rockets',
      quantity: 1,
      flags: 1,
    },
    unique: 599,
    tokenizedName: 'refurbished_tinker_shadowflame_rockets',
    slot: 'socket',
    socketType: 'TINKER',
  },
  7526: {
    id: 7526,
    displayName: 'Algari Weaverline',
    spellId: 455829,
    spellIcon: 'trade_engineering',
    itemId: 225729,
    itemName: 'Algari Weaverline',
    itemIcon: 'inv_tailoring_80_nylonthread',
    tokenizedName: 'algari_weaverline',
  },
  7529: {
    id: 7529,
    displayName: '593 Int & +3% Mana',
    spellId: 457618,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color1',
    itemId: 222894,
    itemName: 'Daybreak Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityOne,
    tokenizedName: 'daybreak_spellthread_1',
    stats: [{type: 'int', amount: 593}],
    spellEffects: [457615],
  },
  7530: {
    id: 7530,
    displayName: '670 Int & +4% Mana',
    spellId: 457619,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color1',
    itemId: 222895,
    itemName: 'Daybreak Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityTwo,
    tokenizedName: 'daybreak_spellthread_2',
    stats: [{type: 'int', amount: 670}],
    spellEffects: [457616],
  },
  7531: {
    id: 7531,
    displayName: '747 Int & +5% Mana',
    spellId: 457620,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color1',
    itemId: 222896,
    itemName: 'Daybreak Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityThree,
    tokenizedName: 'daybreak_spellthread_3',
    stats: [{type: 'int', amount: 747}],
    spellEffects: [457617],
  },
  7532: {
    id: 7532,
    displayName: '593 Int & 180 Sta',
    spellId: 457621,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color2',
    itemId: 222891,
    itemName: 'Sunset Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityOne,
    tokenizedName: 'sunset_spellthread_1',
    stats: [
      {type: 'int', amount: 593},
      {type: 'sta', amount: 180},
    ],
  },
  7533: {
    id: 7533,
    displayName: '670 Int & 211 Sta',
    spellId: 457622,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color2',
    itemId: 222892,
    itemName: 'Sunset Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityTwo,
    tokenizedName: 'sunset_spellthread_2',
    stats: [
      {type: 'int', amount: 670},
      {type: 'sta', amount: 211},
    ],
  },
  7534: {
    id: 7534,
    displayName: '747 Int & 230 Sta',
    spellId: 457623,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color2',
    itemId: 222893,
    itemName: 'Sunset Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityThree,
    tokenizedName: 'sunset_spellthread_3',
    stats: [
      {type: 'int', amount: 747},
      {type: 'sta', amount: 230},
    ],
  },
  7535: {
    id: 7535,
    displayName: '479 Int',
    spellId: 457624,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    itemId: 222888,
    itemName: 'Weavercloth Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityOne,
    tokenizedName: 'weavercloth_spellthread_1',
    stats: [{type: 'int', amount: 479}],
  },
  7536: {
    id: 7536,
    displayName: '536 Int',
    spellId: 457625,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    itemId: 222889,
    itemName: 'Weavercloth Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityTwo,
    tokenizedName: 'weavercloth_spellthread_2',
    stats: [{type: 'int', amount: 536}],
  },
  7537: {
    id: 7537,
    displayName: '593 Int',
    spellId: 457626,
    spellIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    itemId: 222890,
    itemName: 'Weavercloth Spellthread',
    itemIcon:
      'inv_10_tailoring_craftingoptionalreagent_enhancedspellthread_color3',
    craftingQuality: qualityThree,
    tokenizedName: 'weavercloth_spellthread_3',
    stats: [{type: 'int', amount: 593}],
  },

  7593: {
    id: 7593,
    displayName: '650 Agi/Str & 690 Armor',
    spellId: 451826,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219906,
    itemName: "Defender's Armor Kit",
    itemIcon: 'inv_armorkit_arathi',
    craftingQuality: qualityOne,
    tokenizedName: 'defenders_armor_kit_1',
    stats: [{type: 'stragi', amount: 650}],
  },
  7594: {
    id: 7594,
    displayName: '790 Agi/Str & 835 Armor',
    spellId: 451827,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219907,
    itemName: "Defender's Armor Kit",
    itemIcon: 'inv_armorkit_arathi',
    craftingQuality: qualityTwo,
    tokenizedName: 'defenders_armor_kit_2',
    stats: [{type: 'stragi', amount: 790}],
  },
  7595: {
    id: 7595,
    displayName: '930 Agi/Str & 980 Armor',
    spellId: 451828,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219908,
    itemName: "Defender's Armor Kit",
    itemIcon: 'inv_armorkit_arathi',
    craftingQuality: qualityThree,
    tokenizedName: 'defenders_armor_kit_3',
    stats: [{type: 'stragi', amount: 930}],
  },
  7596: {
    id: 7596,
    displayName: '430 Agi/Str',
    spellId: 451829,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219912,
    itemName: 'Dual Layered Armor Kit',
    itemIcon: 'inv_armorkit_standard',
    craftingQuality: qualityOne,
    tokenizedName: 'dual_layered_armor_kit_1',
    stats: [{type: 'stragi', amount: 430}],
  },
  7597: {
    id: 7597,
    displayName: '525 Agi/Str',
    spellId: 451830,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219913,
    itemName: 'Dual Layered Armor Kit',
    itemIcon: 'inv_armorkit_standard',
    craftingQuality: qualityTwo,
    tokenizedName: 'dual_layered_armor_kit_2',
    stats: [{type: 'stragi', amount: 525}],
  },
  7598: {
    id: 7598,
    displayName: '620 Agi/Str',
    spellId: 451831,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219914,
    itemName: 'Dual Layered Armor Kit',
    itemIcon: 'inv_armorkit_standard',
    craftingQuality: qualityThree,
    tokenizedName: 'dual_layered_armor_kit_3',
    stats: [{type: 'stragi', amount: 620}],
  },
  7599: {
    id: 7599,
    displayName: '650 Agi/Str & 625 Sta',
    spellId: 451821,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219909,
    itemName: 'Stormbound Armor Kit',
    itemIcon: 'inv_armorkit_lightning_imbued',
    craftingQuality: qualityOne,
    tokenizedName: 'stormbound_armor_kit_1',
    stats: [
      {type: 'sta', amount: 625},
      {type: 'stragi', amount: 650},
    ],
  },
  7600: {
    id: 7600,
    displayName: '790 Agi/Str & 760 Sta',
    spellId: 451824,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219910,
    itemName: 'Stormbound Armor Kit',
    itemIcon: 'inv_armorkit_lightning_imbued',
    craftingQuality: qualityTwo,
    tokenizedName: 'stormbound_armor_kit_2',
    stats: [
      {type: 'sta', amount: 760},
      {type: 'stragi', amount: 790},
    ],
  },
  7601: {
    id: 7601,
    displayName: '930 Agi/Str & 895 Sta',
    spellId: 451825,
    spellIcon: 'inv_10_skinning_consumable_armorkit_color2',
    itemId: 219911,
    itemName: 'Stormbound Armor Kit',
    itemIcon: 'inv_armorkit_lightning_imbued',
    craftingQuality: qualityThree,
    tokenizedName: 'stormbound_armor_kit_3',
    stats: [
      {type: 'sta', amount: 895},
      {type: 'stragi', amount: 930},
    ],
  },
}
